[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
refreshPeriod = "168h"

[".vim"]
type = "git-repo"
url = "https://github.com/tadpol/vimrc.git"
refreshPeriod = "168h"
clone.args = ["--recurse-submodules"]

